/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package keretaapi.selina;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.MessageFormat;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTable.PrintMode;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Shelin
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        tfNama = new javax.swing.JTextField();
        tfId = new javax.swing.JTextField();
        tfAsal = new javax.swing.JTextField();
        tfTujuan = new javax.swing.JTextField();
        dateChooser = new com.toedter.calendar.JDateChooser();
        jenis = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbWaktu = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        tfJumlah = new javax.swing.JTextField();
        cbGerbong = new javax.swing.JComboBox<>();
        tfHarga = new javax.swing.JTextField();
        btnShow = new javax.swing.JButton();
        btnPesan = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tData = new javax.swing.JTable();
        btnHapus = new javax.swing.JButton();
        btnPrint = new javax.swing.JButton();
        btnSignout = new javax.swing.JButton();

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Stasiun Keberangkatan");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Harga");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(480, 250, 180, 15);

        jLabel4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nama Pemesan");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 90, 160, 15);

        jLabel5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("No ID");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(20, 130, 130, 15);

        jLabel7.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Stasiun Keberangkatan");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(20, 170, 180, 15);

        jLabel8.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Jumlah Tiket");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(20, 250, 160, 15);

        jLabel9.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Tanggal Keberangkatan");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(480, 90, 190, 15);

        jLabel10.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Jenis Kereta");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(480, 130, 180, 15);

        jLabel11.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Waktu Keberangkatan");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(480, 170, 180, 15);

        jLabel12.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Gerbong");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(480, 210, 180, 15);
        jPanel1.add(tfNama);
        tfNama.setBounds(210, 80, 260, 30);
        jPanel1.add(tfId);
        tfId.setBounds(210, 120, 260, 30);
        jPanel1.add(tfAsal);
        tfAsal.setBounds(210, 160, 260, 30);
        jPanel1.add(tfTujuan);
        tfTujuan.setBounds(210, 200, 260, 30);
        jPanel1.add(dateChooser);
        dateChooser.setBounds(620, 80, 210, 30);

        jenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Pilih Salah Satu-", "Eksekutif", "Bisnis", "Ekonomi" }));
        jPanel1.add(jenis);
        jenis.setBounds(620, 120, 210, 30);

        jPanel3.setBackground(new java.awt.Color(255, 102, 0));
        jPanel3.setLayout(null);
        jPanel1.add(jPanel3);
        jPanel3.setBounds(0, 60, 890, 10);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial Unicode MS", 0, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setText("FORM RESERVASI TIKET KERETA");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(290, 0, 330, 30);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 102));
        jLabel2.setText("PT. KERETA API INDONESIA");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(350, 30, 190, 17);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 890, 60);

        cbWaktu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Pilih Salah Satu-", "05.00 AM", "11.00 AM", "17.00 PM", "20.00 PM", "02.00 AM", " ", " ", " " }));
        cbWaktu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbWaktuActionPerformed(evt);
            }
        });
        jPanel1.add(cbWaktu);
        cbWaktu.setBounds(620, 160, 210, 30);

        jLabel13.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Stasiun Tujuan");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(20, 210, 160, 15);
        jPanel1.add(tfJumlah);
        tfJumlah.setBounds(210, 240, 260, 30);

        cbGerbong.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Pilih Salah Satu-", "Gerbong 1", "Gerbong 2", "Gerbong 3", "Gerbong 4", "Gerbong 5" }));
        jPanel1.add(cbGerbong);
        cbGerbong.setBounds(620, 200, 210, 30);
        jPanel1.add(tfHarga);
        tfHarga.setBounds(620, 240, 260, 30);

        btnShow.setBackground(new java.awt.Color(255, 102, 0));
        btnShow.setText("UPDATE");
        btnShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowActionPerformed(evt);
            }
        });
        jPanel1.add(btnShow);
        btnShow.setBounds(410, 290, 90, 30);

        btnPesan.setBackground(new java.awt.Color(255, 102, 0));
        btnPesan.setText("PESAN");
        btnPesan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesanActionPerformed(evt);
            }
        });
        jPanel1.add(btnPesan);
        btnPesan.setBounds(210, 290, 90, 30);

        btnClear.setBackground(new java.awt.Color(255, 102, 0));
        btnClear.setText("CLEAR");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        jPanel1.add(btnClear);
        btnClear.setBounds(310, 290, 90, 30);

        tData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nama", "No ID", "Stasiun Keberangkatan", "Stasiun Tujuan", "Jumlah ", "Tanggal Keberangkatan", "Jenis", "Waktu Keberangkatan", "Tempat Duduk", "Harga"
            }
        ));
        jScrollPane2.setViewportView(tData);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(0, 340, 880, 270);

        btnHapus.setBackground(new java.awt.Color(255, 102, 0));
        btnHapus.setText("HAPUS");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });
        jPanel1.add(btnHapus);
        btnHapus.setBounds(510, 290, 100, 30);

        btnPrint.setBackground(new java.awt.Color(255, 102, 0));
        btnPrint.setText("PRINT");
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });
        jPanel1.add(btnPrint);
        btnPrint.setBounds(620, 290, 100, 30);

        btnSignout.setBackground(new java.awt.Color(255, 102, 0));
        btnSignout.setText("SIGN OUT");
        btnSignout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignoutActionPerformed(evt);
            }
        });
        jPanel1.add(btnSignout);
        btnSignout.setBounds(730, 290, 100, 30);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 620));

        setSize(new java.awt.Dimension(902, 653));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnPesanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesanActionPerformed
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String tanggal = dateFormat.format(dateChooser.getDate());
        if ("".equals(tfNama.getText()) || "".equals(tfId.getText()) || "".equals(tfAsal.getText()) || "".equals(tfTujuan.getText()) || "".equals(tfJumlah.getText())) {
            JOptionPane.showMessageDialog(this, "Harap Lengkapi Data!","Error",JOptionPane.WARNING_MESSAGE);
        } else{           
            String Jenis = "";
            if (jenis.getSelectedItem().equals("Eksekutif")) {
                Jenis = "Eksekutif";
            }
            else if (jenis.getSelectedItem().equals("Bisnis")){
                Jenis = "Bisnis";
            }
            else if (jenis.getSelectedItem().equals("Ekonomi")) {
                Jenis = "Ekonomi";
        
            
            } String Waktu ="";
            if (cbWaktu.getSelectedItem().equals("05.00 AM")) {
                Waktu = "05.00 PM";
            }
            else if (cbWaktu.getSelectedItem().equals("11.00 AM")) {
                Waktu = "11.00 PM";
            }
            else if (cbWaktu.getSelectedItem().equals("17.00 PM")) {
                Waktu = "17.00 PM";
            }
            else if (cbWaktu.getSelectedItem().equals("20.00 PM")) {
                Waktu = "20.00 PM";
            }
            else if (cbWaktu.getSelectedItem().equals("02.00 PM")) {
                Waktu = "02.00 AM";
            
            } String Gerbong = "";
            if(cbGerbong.getSelectedItem().equals("Gerbong 1")) {
                Gerbong  = "Gerbong 1";
            }
            else if (cbGerbong.getSelectedItem().equals("Gerbong 2")) {
                Gerbong = "Gerbong 2";
            }
            else if (cbGerbong.getSelectedItem().equals("Gerbong 3")){
                Gerbong = "Gerbong 3";
            }
            else if (cbGerbong.getSelectedItem().equals("Gerbong 4")) {
                Gerbong = "Gerbong 4";
            }
            else if(cbGerbong.getSelectedItem().equals("Gerbong 5")) {
                Gerbong = "Gerbong 5";
            }   
            String SQL = "INSERT INTO tb_pemesanan (nama,noid,awal,tujuan,jumlah,tanggal,jenis,waktu,seat,harga) VALUES ('"+tfNama.getText()+"','"+tfId.getText()+"','"+tfAsal.getText()+"','"+tfTujuan.getText()+"','"+tfJumlah.getText()+"','"+tanggal+"','"+Jenis+"','"+Waktu+"','"+Gerbong+"','"+tfHarga.getText()+"')";
            int status = KoneksiDB.execute(SQL);
        if (status == 1) {
            JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan","Sukses",JOptionPane.INFORMATION_MESSAGE);
           
        }else{
            JOptionPane.showMessageDialog(this, "Data gagal ditambahkan","Gagal",JOptionPane.WARNING_MESSAGE);
        }
        } 
    }//GEN-LAST:event_btnPesanActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        tfNama.setText("");
        tfId.setText("");
        tfAsal.setText("");
        tfTujuan.setText("");
        tfJumlah.setText("");
        dateChooser.setCalendar(null);        
        jenis.setSelectedItem("-Pilih Salah Satu-");
        cbWaktu.setSelectedItem("-Pilih Salah Satu-");
        cbGerbong.setSelectedItem("-Pilih Salah Satu-");
        tfHarga.setText("");
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowActionPerformed
       selectData();
            
    }//GEN-LAST:event_btnShowActionPerformed

    private void cbWaktuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbWaktuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbWaktuActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        int baris = tData.getSelectedRow();
        if(baris != -1) {
            String noid = tData.getValueAt(baris, 1).toString();
            String SQL = "DELETE FROM tb_pemesanan WHERE noid ='"+noid+"'";
            int status = KoneksiDB.execute(SQL);
            if (status==1) {
                JOptionPane.showMessageDialog(this, "Data berhasil dihapus", "Sukses", JOptionPane.INFORMATION_MESSAGE);
            }else{
                JOptionPane.showMessageDialog(this, "Data gagal dihapus","Gagal",JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Pilih baris data terlebih dahulu","Error",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        MessageFormat header = new MessageFormat("Reservasi Tiket Kereta Api");
        MessageFormat footer = new MessageFormat("Page {0,number,integer}");
        try {
              tData.print(JTable.PrintMode.FIT_WIDTH,header,footer,true,null,true,null);
        } catch (java.awt.print.PrinterException e) {
            System.err.format("Cannot print %s%n", e.getMessage());
        }
    }//GEN-LAST:event_btnPrintActionPerformed

    private void btnSignoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignoutActionPerformed
        new Login().show();
            this.dispose();
    }//GEN-LAST:event_btnSignoutActionPerformed

    /**
     * 
     * @param args 
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnPesan;
    private javax.swing.JButton btnPrint;
    private javax.swing.JButton btnShow;
    private javax.swing.JButton btnSignout;
    private javax.swing.JComboBox<String> cbGerbong;
    private javax.swing.JComboBox<String> cbWaktu;
    private com.toedter.calendar.JDateChooser dateChooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox<String> jenis;
    private javax.swing.JTable tData;
    private javax.swing.JTextField tfAsal;
    private javax.swing.JTextField tfHarga;
    private javax.swing.JTextField tfId;
    private javax.swing.JTextField tfJumlah;
    private javax.swing.JTextField tfNama;
    private javax.swing.JTextField tfTujuan;
    // End of variables declaration//GEN-END:variables

    private void selectData() {
        String kolom[] = {"nama","noid","awal","tujuan","jumlah","tanggal","jenis","waktu","seat","harga"};
                DefaultTableModel dtm = new DefaultTableModel(null, kolom);
                String SQL ="SELECT * FROM tb_pemesanan";
                ResultSet rs = KoneksiDB.executeQuery(SQL);
                try{
                    while(rs.next()){
                        String nama = rs.getString(1);
                        String id = rs.getString(2);
                        String brgkt = rs.getString(3);
                        String tujuan = rs.getString(4);
                        String jmlh = rs.getString(5);
                        String tgl = rs.getString(6);
                        String jns = rs.getString(7);
                        if ("Eksekutif".equals(rs.getString(7))){
                            jns = "Eksekutif";
                        }else if ("Bisnis".equals(rs.getString(7))){
                            jns = "Bisnis";
                        }else if ("Ekonomi".equals(rs.getString(7))){
                            jns ="Ekonomi";
                        }                       
                        String waktu = rs.getString(8);
                        if ("05.00 AM".equals(rs.getString(8))){
                            waktu = "05.00 AM";
                        } else if("11.00 AM".equals(rs.getString(8))){
                            waktu = "11.00 AM";
                        } else if ("17.00 PM".equals(rs.getString(8))){
                            waktu = "17.00 PM";
                        } else if ("20.00 PM".equals(rs.getString(8))){
                            waktu = "20.00 PM";
                        } else if ("02.00 AM".equals(rs.getString(8))){
                            waktu = "02.00 AM";
                        }
                        String seat = rs.getString(9);
                        if ("Gerbong 1".equals(rs.getString(9))){
                            seat = "Gerbong 1";
                        } else if ("Gerbong 2".equals(rs.getString(9))){
                            seat = "Gerbong 2";
                        }  else if ("Gerbong 3".equals(rs.getString(9))){
                            seat = "Gerbong 3";
                        }  else if ("Gerbong 4".equals(rs.getString(9))){
                            seat = "Gerbong 4";
                        }  else if ("Gerbong 5".equals(rs.getString(9))){
                            seat = "Gerbong 5";
                        }
                        String harga = rs.getString(10);
                        String data[] = {nama,id,brgkt,tujuan,jmlh,tgl,jns,waktu,seat,harga};
                        dtm.addRow(data);
                    }
                    } catch (SQLException ex) {
                       Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE,null,ex);
                }
                tData.setModel(dtm);
    }
}
